//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPS08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTO
    {
        public int IDauto { get; set; }
        public string Marca { get; set; }
        public Nullable<int> miEstatus { get; set; }
        public string ImgRuta { get; set; }
        public string Modelo { get; set; }
        public string Anio { get; set; }
    
        public virtual VHESTATU VHESTATU { get; set; }
    }
}
