//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPS08.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMVCSCEntities : DbContext
    {
        public DBMVCSCEntities()
            : base("name=DBMVCSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mStatu> mStatus { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<AUTO> AUTOS { get; set; }
        public virtual DbSet<VHESTATU> VHESTATUS { get; set; }
    }
}
